-- CaptionAI — full Supabase schema (run once in SQL Editor, in order).
-- Combines: step3_schema + caption_history + step5_stripe_portal + features_restore.

-- ═══ STEP 3: usage + subscriptions ═══════════════════════════════════════════

create table if not exists public.usage (
  id int8 generated by default as identity primary key,
  user_id text not null,
  date date not null,
  count int4 not null default 0
);

create unique index if not exists usage_user_id_date_key
  on public.usage (user_id, date);

create table if not exists public.subscriptions (
  id int8 generated by default as identity primary key,
  user_id text not null unique,
  plan text not null default 'free',
  updated_at timestamp not null default now()
);

-- ═══ Caption history ══════════════════════════════════════════════════════════

create extension if not exists "pgcrypto";

create table if not exists public.caption_history (
  id uuid primary key default gen_random_uuid (),
  user_id text not null,
  topic text not null,
  platform text not null,
  tone text not null,
  captions jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists caption_history_user_created_idx
  on public.caption_history (user_id, created_at desc);

alter table public.caption_history
  add column if not exists language text not null default 'English';

-- ═══ Stripe customer id (billing portal) ═════════════════════════════════════

alter table public.subscriptions
  add column if not exists stripe_customer_id text;

-- ═══ Feature tables (referrals, favorites, ratings, A/B, admin logs) ═══════

create table if not exists public.caption_favorites (
  user_id text not null,
  history_id uuid not null references public.caption_history (id) on delete cascade,
  caption_index int not null check (caption_index >= 0),
  created_at timestamptz not null default now(),
  primary key (user_id, history_id, caption_index)
);

create index if not exists caption_favorites_user_idx on public.caption_favorites (user_id);

create table if not exists public.caption_ratings (
  user_id text not null,
  history_id uuid not null references public.caption_history (id) on delete cascade,
  caption_index int not null check (caption_index >= 0),
  rating text not null check (rating in ('worst', 'medium', 'best')),
  updated_at timestamptz not null default now(),
  primary key (user_id, history_id, caption_index)
);

create index if not exists caption_ratings_user_idx on public.caption_ratings (user_id);

create table if not exists public.referral_codes (
  user_id text primary key,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.referral_claims (
  id uuid primary key default gen_random_uuid (),
  referrer_user_id text not null,
  referred_user_id text not null unique,
  code text not null,
  created_at timestamptz not null default now()
);

create index if not exists referral_claims_referrer_idx on public.referral_claims (referrer_user_id);

create table if not exists public.ab_experiments (
  id uuid primary key default gen_random_uuid (),
  user_id text not null,
  label text,
  variant_a text not null,
  variant_b text not null,
  picks_a int not null default 0,
  picks_b int not null default 0,
  platform text,
  created_at timestamptz not null default now()
);

create index if not exists ab_experiments_user_idx on public.ab_experiments (user_id, created_at desc);

create table if not exists public.admin_logs (
  id uuid primary key default gen_random_uuid (),
  level text not null default 'info' check (level in ('info', 'warn', 'error')),
  message text not null,
  meta jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_logs_created_idx on public.admin_logs (created_at desc);
create index if not exists admin_logs_level_idx on public.admin_logs (level, created_at desc);
