-- Run this in Supabase SQL Editor.
-- It creates the two required tables for Step 3.

create table if not exists public.usage (
  id int8 generated by default as identity primary key,
  user_id text not null,
  date date not null,
  count int4 not null default 0
);

create unique index if not exists usage_user_id_date_key
  on public.usage (user_id, date);

create table if not exists public.subscriptions (
  id int8 generated by default as identity primary key,
  user_id text not null unique,
  plan text not null default 'free',
  updated_at timestamp not null default now()
);
