import "server-only";

/**
 * Hardcoded blocklist of well-known disposable / temporary email providers.
 * Keeping this static avoids a runtime dependency on an external service
 * (which would also be a tracking vector). The list intentionally focuses
 * on the most-abused domains; expand it over time from real signups.
 */
const DISPOSABLE_DOMAINS: ReadonlySet<string> = new Set([
  "0-mail.com",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "33mail.com",
  "anonbox.net",
  "anonymbox.com",
  "burnermail.io",
  "byom.de",
  "cs.email",
  "deadaddress.com",
  "dispostable.com",
  "dropmail.me",
  "e4ward.com",
  "easytrashmail.com",
  "email-fake.com",
  "email-temp.com",
  "emailondeck.com",
  "emailtemporanea.net",
  "fakeinbox.com",
  "fakemailgenerator.com",
  "fakemail.net",
  "fakermail.com",
  "fastmail.fm",
  "filzmail.com",
  "freemail.ms",
  "front14.org",
  "getairmail.com",
  "getmails.eu",
  "getnada.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "hostalias.com",
  "incognitomail.com",
  "incognitomail.net",
  "inboxbear.com",
  "inboxkitten.com",
  "inboxalias.com",
  "instantemailaddress.com",
  "jetable.org",
  "kasmail.com",
  "luxusmail.org",
  "mailbidon.com",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailguard.me",
  "mailhz.me",
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "mailmoat.com",
  "mailnator.com",
  "mailnesia.com",
  "mailpoof.com",
  "mailsac.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailzilla.com",
  "meltmail.com",
  "mintemail.com",
  "mohmal.com",
  "monumentmail.com",
  "moot.es",
  "mt2014.com",
  "mt2015.com",
  "mt2016.com",
  "mt2017.com",
  "mt2018.com",
  "mt2019.com",
  "mt2020.com",
  "mt2021.com",
  "mt2022.com",
  "mt2023.com",
  "mt2024.com",
  "mt2025.com",
  "muehlmail.com",
  "mvrht.com",
  "mytemp.email",
  "mytempemail.com",
  "mytrashmail.com",
  "nada.email",
  "neverbox.com",
  "no-spam.ws",
  "nomail.xl.cx",
  "noref.in",
  "notmailinator.com",
  "nowmymail.com",
  "objectmail.com",
  "odaymail.com",
  "oneoffmail.com",
  "onewaymail.com",
  "opentrash.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "pjjkp.com",
  "pokemail.net",
  "pokemonpost.com",
  "proxymail.eu",
  "prtnx.com",
  "puji.pro",
  "quickinbox.com",
  "rcpt.at",
  "receiveee.com",
  "rmqkr.net",
  "rootfest.net",
  "sharklasers.com",
  "shieldedmail.com",
  "shitmail.me",
  "shortmail.net",
  "sneakemail.com",
  "snkmail.com",
  "sogetthis.com",
  "spam4.me",
  "spambog.com",
  "spambooger.com",
  "spambox.us",
  "spamcero.com",
  "spamdecoy.net",
  "spamex.com",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgourmet.com",
  "spamherelots.com",
  "spamhole.com",
  "spaml.com",
  "spamoff.de",
  "spamspot.com",
  "spamthis.co.uk",
  "spoofmail.de",
  "superrito.com",
  "tafmail.com",
  "talkinator.com",
  "teleworm.com",
  "teleworm.us",
  "tempail.com",
  "tempemail.com",
  "tempemail.net",
  "tempinbox.com",
  "tempinbox.co.uk",
  "tempmail.de",
  "tempmail.email",
  "tempmail.eu",
  "tempmail.io",
  "tempmail.it",
  "tempmail.net",
  "tempmail.org",
  "tempmail.pro",
  "tempmail.us",
  "tempmail.ws",
  "tempmail2.com",
  "tempmailer.com",
  "tempmailer.de",
  "tempmailo.com",
  "tempomail.fr",
  "temporarily.de",
  "temporary-mail.net",
  "temporaryemail.net",
  "temporaryemail.us",
  "temporaryinbox.com",
  "temp-mail.org",
  "temp-mail.io",
  "temp-mail.ru",
  "thrott.com",
  "throwam.com",
  "throwawaymail.com",
  "throwaway.email",
  "tmailinator.com",
  "tmpbox.net",
  "tmpemails.com",
  "tmpmail.net",
  "tmpmail.org",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "trashymail.com",
  "trbvm.com",
  "trillianpro.com",
  "veryrealemail.com",
  "vmailing.com",
  "vomoto.com",
  "wegwerfemail.com",
  "wegwerfemail.de",
  "wegwerfemail.net",
  "wegwerfmail.de",
  "wegwerfmail.info",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wetrainbayarea.com",
  "wh4f.org",
  "whoismind.com",
  "wmail.cf",
  "xemaps.com",
  "xoxy.net",
  "yepmail.net",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.gq",
  "yopmail.net",
  "zoaxe.com",
  "zoemail.com",
  "zoemail.net",
  "zoemail.org",
]);

export const DISPOSABLE_EMAIL_ERROR_MESSAGE =
  "Please use a real email address to sign up.";

function extractDomain(email: string): string | null {
  const at = email.lastIndexOf("@");
  if (at < 0) return null;
  const domain = email.slice(at + 1).trim().toLowerCase();
  if (!domain || !domain.includes(".")) return null;
  return domain;
}

/**
 * Returns true if the email's domain (or any of its parent suffixes)
 * matches a known disposable provider. Sub-domains of disposable
 * providers are blocked too — e.g. `inbox.mailinator.com` matches
 * `mailinator.com`.
 */
export function isDisposableEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  const domain = extractDomain(email);
  if (!domain) return false;
  if (DISPOSABLE_DOMAINS.has(domain)) return true;

  const parts = domain.split(".");
  for (let i = 1; i < parts.length - 1; i++) {
    const suffix = parts.slice(i).join(".");
    if (DISPOSABLE_DOMAINS.has(suffix)) return true;
  }
  return false;
}

export function getDisposableDomainCount(): number {
  return DISPOSABLE_DOMAINS.size;
}
